name: post-results

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: run-job
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: python3.10 -m venv venv; source venv/bin/activate; pip install -r requirements.txt
      - name: Check branch
        run: git branch
      - name: Run main.py
        env:
          LOCALLY_RUN: false
          SLACK_HOOK_COURSEGRAB_URL: ${{ secrets.SLACK_HOOK_COURSEGRAB_URL }}
          SLACK_HOOK_EATERY_URL: ${{ secrets.SLACK_HOOK_EATERY_URL }}
          SLACK_HOOK_TRANSIT_URL: ${{ secrets.SLACK_HOOK_TRANSIT_URL }}
          SLACK_HOOK_UPLIFT_URL: ${{ secrets.SLACK_HOOK_UPLIFT_URL }}
          SLACK_HOOK_VOLUME_URL: ${{ secrets.SLACK_HOOK_VOLUME_URL }}
          ADMIN_SLACK_USER_IDS: ${{ secrets.ADMIN_SLACK_USER_IDS }}
          EATERY_SLACK_USER_IDS: ${{ secrets.EATERY_SLACK_USER_IDS }}
          TRANSIT_SLACK_USER_IDS: ${{ secrets.TRANSIT_SLACK_USER_IDS }}
          UPLIFT_SLACK_USER_IDS: ${{ secrets.UPLIFT_SLACK_USER_IDS }}
          VOLUME_SLACK_USER_IDS: ${{ secrets.VOLUME_SLACK_USER_IDS }}
          EATERY_BACKEND_URL: ${{ secrets.EATERY_BACKEND_URL }}
          TRANSIT_BACKEND_URL: ${{ secrets.TRANSIT_BACKEND_URL }}
          TRANSIT_DEV_BACKEND_URL: ${{ secrets.TRANSIT_DEV_BACKEND_URL }}
          UPLIFT_BACKEND_URL: ${{ secrets.UPLIFT_BACKEND_URL }}
          VOLUME_BACKEND_URL: ${{ secrets.VOLUME_BACKEND_URL }}
        run: source venv/bin/activate; python src/main.py --use-config >> $GITHUB_ENV
      - name: Save the config
        run: |
          echo ${{ env.ORIGINAL_CONFIG }}
          echo ${{ env.TEST_CONFIG }} > src/test_config.txt
        if: env.ORIGINAL_CONFIG != env.TEST_CONFIG
        run: |
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate test_config"
          git push
